<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Abstractions\**" />
    <EmbeddedResource Remove="Abstractions\**" />
    <None Remove="Abstractions\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DineDrop.Domain\DineDrop.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Modules\Drivers\DTOs\" />
    <Folder Include="Modules\Drivers\Commands\" />
    <Folder Include="Modules\Drivers\Handlers\" />
    <Folder Include="Modules\Drivers\Queries\" />
    <Folder Include="Modules\Orders\Commands\" />
    <Folder Include="Modules\Orders\DTOs\" />
    <Folder Include="Modules\Orders\Handlers\" />
    <Folder Include="Modules\Orders\Queries\" />
    <Folder Include="Modules\Restaurants\Commands\" />
  </ItemGroup>

</Project>
